devtools:
  livereload:
    enabled: 'true'
spring:
  profiles:
    group:
      local:
        - db
        - oauth
  thymeleaf:
    cache: 'false'
  mvc:
    converters:
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: 'true'
      max-request-size: 30MB
      location: C:\upload
logging:
  level:
    org:
      springframework: INFO
server:
  port: 8081