devtools:
  livereload:
    enabled: 'true'
spring:
  thymeleaf:
    cache: 'false'
  mvc:
    converters:
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: 'true'
      max-request-size: 30MB
      location: C:\upload
  datasource:
    password: thdusektmf
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    hikari:
      maximum-pool-size: '3'
    url: jdbc:mysql://sd-housemate.cnbnt4friika.ap-northeast-2.rds.amazonaws.com/housematedb
mybatis:
  type-aliases-package: com.example.demo
logging:
  level:
    org:
      springframework: INFO
