spring:
  config:
    activate:
      on-profile: mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: devzzang94@gmail.com
    password: unctmbnuavhmiqsq
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000