devtools:
  livereload:
    enabled: 'true'
spring:
  profiles:
    group:
      local:
        - db
        - oauth
        - app
        - mail
  thymeleaf:
    cache: 'false'
  mvc:
    converters:
      preferred-json-mapper: gson
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: 'true'
      max-request-size: 30MB
      location: E:\\workspace\\spring-upload\\
  main:
    allow-circular-references: true
logging:
  level:
    org:
      springframework: INFO
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true